apiVersion: v1
kind: Service
metadata:
    name: app-lb-svc
spec:
    ports:
        -   name: http
            port: 3001
            targetPort: 3001
            protocol: TCP
    selector:
        app: app-pod
    type: LoadBalancer