apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: app-pvc
spec:
    storageClassName: manual
    accessModes:
        -   ReadWriteOnce
    resources:
        requests:
            storage: 200Mi